AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/MixinUsage:
  Enabled: false